# Generated by Django 2.1.7 on 2019-04-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20190411_0800'),
        ('pagos', '0002_userplanpaypalbill'),
    ]

    operations = [
    ]
