# Generated by Django 2.1.7 on 2019-04-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_merge_20190411_1816'),
        ('pagos', '0004_merge_20190411_2213'),
    ]

    operations = [
    ]
