# Generated by Django 2.1.7 on 2019-04-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='isPayed',
            field=models.BooleanField(default=False),
        ),
    ]
