# Generated by Django 2.1.7 on 2019-04-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0002_userplan_ispayed'),
        ('datame', '0002_auto_20190411_2237'),
    ]

    operations = [
    ]
