# Generated by Django 2.2 on 2019-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(max_length=1000, verbose_name='comments'),
        ),
    ]
