# Generated by Django 2.2 on 2019-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0003_auto_20190423_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Apply description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=1000, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract',
            field=models.TextField(max_length=2000, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Offer description'),
        ),
        migrations.AlterField(
            model_name='submition',
            name='comments',
            field=models.TextField(max_length=1000, verbose_name='Comments'),
        ),
    ]
