# Generated by Django 2.2 on 2019-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0004_auto_20190423_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
